name: Pipeline
on: [push]

jobs:
  test_and_build:
    name: Test and build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2.3.4
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: v0.6.0
          buildkitd-flags: --debug
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build start target
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          target: start
          tags: axiix/angular-starter-reference:start
          cache-from: type=gha, scope=${{ github.workflow }}
          cache-to: type=gha, scope=${{ github.workflow }}
      - name: Build test target
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          load: true
          target: test
          tags: axiix/angular-starter-reference:test
          cache-from: type=gha, scope=${{ github.workflow }}
          cache-to: type=gha, scope=${{ github.workflow }}
      - name: Build target
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          target: builder
          tags: axiix/angular-starter-reference:build
          cache-from: type=gha, scope=${{ github.workflow }}
          cache-to: type=gha, scope=${{ github.workflow }}
      - name: Build final target
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          target: runtime
          tags: axiix/angular-starter-reference:${{ steps.tag_version.outputs.new_tag }}
          cache-from: type=gha, scope=${{ github.workflow }}
          cache-to: type=gha, scope=${{ github.workflow }}
      - name: Prepare helm chart
        run: |
          sed -i -e "s/BUILD_VERSION/${{ steps.tag_version.outputs.new_tag }}/g" charts/angular-starter-reference/Chart.yaml
          sed -i -e "s/HELM_VERSION/${{ steps.tag_version.outputs.new_version }}/g" charts/angular-starter-reference/Chart.yaml
          sed -i -e "s/BUILD_VERSION/${{ steps.tag_version.outputs.new_tag }}/g" charts/angular-starter-reference/values.yaml
      - name: Extract coverage
        id: extract_coverage
        uses: shrink/actions-docker-extract@v1
        with:
          image: axiix/angular-starter-reference:test
          path: /usr/src/app/coverage/angular-starter/.
      - name: Extract junit
        id: extract_junit
        uses: shrink/actions-docker-extract@v1
        with:
          image: axiix/angular-starter-reference:test
          path: /usr/src/app/junit/.
      - name: Upload Coverage
        uses: actions/upload-artifact@v2
        with:
          path: ${{ steps.extract_coverage.outputs.destination }}
          name: coverage
      - name: Upload Junit
        uses: actions/upload-artifact@v2
        with:
          path: ${{ steps.extract_junit.outputs.destination }}
          name: junit
      - name: Upload Helm chart
        uses: actions/upload-artifact@v2
        with:
          path: charts
          name: angular-starter-reference-chart

  deploy:
    name: Deploy application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2.3.4
      - name: AKS set context
        uses: azure/aks-set-context@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}' # Azure credentials
          resourceGroupName: 'web-viewer-tl-20210713-k8'
          clusterName: 'web-viewer-team-learning-20210713-kube'
        id: login
      - name: Install Helm
        uses: azure/setup-helm@v1
        id: install
      - name: Deploy app
        run: |
          helm upgrade --install angular-starter-reference charts/angular-starter-reference/

