name: Pipeline
on: [push]

jobs:
  test_and_build:
    name: Test and build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2.3.4
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: v0.6.0
          buildkitd-flags: --debug
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build start target
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          target: start
          tags: axiix/angular-starter-reference:start
          cache-from: type=gha, scope=${{ github.workflow }}
          cache-to: type=gha, scope=${{ github.workflow }}
      - name: Build test target
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          target: test
          tags: axiix/angular-starter-reference:test
          cache-from: type=gha, scope=${{ github.workflow }}
          cache-to: type=gha, scope=${{ github.workflow }}
      - name: Debug docker images
        run: docker images
      - name: Extract coverage
        id: extract_coverage
        uses: shrink/actions-docker-extract@v1
        with:
          image: axiix/angular-starter-reference:test
          path: /usr/src/app/coverage/angular-starter.
      - name: Upload Coverage
        uses: actions/upload-artifact@v2
        with:
          path: ${{ steps.extract_coverage.outputs.destination }}
          name: coverage
